version: 0.2

phases:
  pre_build:
    commands:
      - npm install --production
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
